### ISSUE TITLE
When doing a search with no results, an exception is thrown

### ISSUE THREAD

**Issue by facundofarias** [chucknorris-io/client-nodejs#1]
Currently, when there are no results while calling to the search, the following error is thrown:

```
TypeError: Cannot read property 'map' of undefined
    at Object.JokeCollectionMapper.fromJson (../Mapper/JokeCollection.js:48:31)
    at JokeCollectionMapper.fromApiResponse (../Mapper/JokeCollection.js:23:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

It should return an empty JokeCollection instead.

**Comment by matchilling** [comment]
Hola @facundofarias,

Thanks for raising this issue 🙏 , unfortunately I couldn't re-create it. Can you please provide more details like the client and node version you're using as well as the search query or other steps which could help to further investigate this bug.

He're is my console output for a [query with search term `eso-no-existe`](https://api.chucknorris.io/jokes/search?query=eso-no-existe) using the latest client version:

```bash
$ node --version
v11.14.0
$ node
> const Chuck = require('./src/Client')
undefined
> const client = new Chuck()
undefined
> client.search("eso-no-existe").then(console.log)
Promise { <pending> }
> JokeCollection { count: 0, items: [] }
```
